### ISSUE TITLE
Error with latest aframe

### ISSUE THREAD

**Issue by KevinGrandon** [maxkrieger/aframe-textwrap-component#3]
I'm seeing the following error when using this library with the latest version of aframe (master not on npm):

```
Uncaught (in promise) TypeError: Cannot read property 'clearRect' of undefined
```

If possible it would be nice to support the latest version of aframe because it has WebVR 1.0 support and will likely be publishing a release to npm soon.

**Comment by maxkrieger** [comment]
Sure, I'll see what I can do

**Comment by Goblinlordx** [comment]
render() in "draw" component is being called prior to a canvas element being created and context being set.  Inside draw component's init() you can call createCanvas to prevent this.

**Comment by maxkrieger** [comment]
@Goblinlordx Thanks for finding this. I've been very busy lately so feel free to hand over a pull request and I'll run it straight through. Otherwise maybe this weekend it'll happen?

**Comment by Goblinlordx** [comment]
:+1:
https://github.com/maxkrieger/aframe-draw-component/pull/5/files

**Comment by maxkrieger** [comment]
Thanks again! 👍
